apiVersion: v1
kind: Namespace
metadata:
  name: doom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doom
  namespace: doom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doom
  template:
    metadata:
      labels:
        app: doom
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      containers:
        - name: doom
          image: ghcr.io/zwindler/kubesolo-pizero/doom-vnc:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VNC_PASSWORD
              value: idbehold
          ports:
            - containerPort: 5900
              name: vnc
          resources:
            requests:
              memory: 16Mi
              cpu: 100m
            limits:
              memory: 32Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: data
              mountPath: /data
          workingDir: /data
      volumes:
        - name: data
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
---
apiVersion: v1
kind: Service
metadata:
  name: doom
  namespace: doom
spec:
  type: NodePort
  selector:
    app: doom
  ports:
    - name: vnc
      port: 5900
      targetPort: vnc
      nodePort: 30900
